name: Build, push and deploy NGINX

on: [workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push NGINX

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USERNAME }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/nginx

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: deploy/dockerfiles/Dockerfile.nginx
          platforms: linux/amd64

  deploy:
    runs-on: ubuntu-latest
    name: Deploy NGINX

    needs:
      - build-and-push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy NGINX
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            docker run --rm -d -p 80:80 -p 443:443 --name evil-cards-master-nginx ghcr.io/adjsky/evil-cards/nginx:master
